# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oliboy50
email: contact@oliver-thebault.com
description: >- # this means to ignore newlines until "baseurl:"
  Oliver Thébault - Développeur Web - Aime les animes, les trophées PSN, les chats et les listes.
twitter_username: OliverThebault
github_username:  Oliboy50
header_pages:
  - animes.md
  - anime-movies.md
  - series.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
